input = [
    "232",
    "99",
    "80",
    "224",
    "45",
    "237",
    "127",
    "252",
    "136",
    "118",
    "61",
    "0",
    "24",
    "2",
    "187",
    "6",
    "11",
    "62",
    "152",
    "14",
    "212",
    "142",
    "226",
    "74",
    "95",
    "251",
    "108",
    "188",
    "8",
    "24",
    "27",
    "56",
    "201",
    "238",
    "73",
    "56",
    "168",
    "0",
    "184",
    "45",
    "3",
    "7",
    "75",
    "83",
    "48",
    "213",
    "135",
    "52",
    "247",
    "12",
    "15",
    "37",
    "141",
    "70",
    "91",
    "183",
    "213",
    "183",
    "64",
    "189",
    "215",
    "3",
    "60",
    "216",
    "206",
    "241",
    "74",
    "138",
    "235",
    "150",
    "209",
    "18",
    "151",
    "160",
    "106",
    "193",
    "125",
    "200",
    "131",
    "180",
    "57",
    "136",
    "184",
    "79",
    "96",
    "253",
    "162",
    "67",
    "236",
    "176",
    "54",
    "201",
    "96",
    "113",
    "109",
    "109",
    "244",
    "146",
    "120",
    "105",
    "30",
    "187",
    "67",
    "175",
    "22",
    "250",
    "103",
    "78",
    "253",
    "134",
    "222",
    "73",
    "184",
    "135",
    "191",
    "106",
    "194",
    "118",
    "159",
    "197",
    "14",
    "188",
    "247",
    "61",
    "55",
    "206",
    "187",
    "236",
    "112",
    "28",
    "226",
    "64",
    "78",
    "105",
    "4",
    "208",
    "138",
    "202",
    "183",
    "223",
    "166",
    "158",
    "64",
    "5",
    "163",
    "0",
    "116",
    "152",
    "204",
    "107",
    "97",
    "169",
    "52",
    "14",
    "115",
    "181",
    "196",
    "140",
    "188",
    "154",
    "102",
    "65",
    "113",
    "149",
    "195",
    "207",
    "255",
    "100",
    "21",
    "193",
    "77",
    "119",
    "137",
    "138",
    "60",
    "169",
    "236",
    "68",
    "140",
    "89",
    "70",
    "163",
    "119",
    "200",
    "184",
    "169",
    "139",
    "241",
    "54",
    "205",
    "0",
    "58",
    "35",
    "26",
    "61",
    "200",
    "164",
    "154",
    "149",
    "227",
    "71",
    "130",
    "80",
    "33",
    "32",
    "24",
    "230",
    "38",
    "226",
    "38",
    "246",
    "162",
    "125",
    "241",
    "170",
    "106",
    "45",
    "240",
    "8",
    "152",
    "221",
    "53",
    "39",
    "54",
    "50",
    "251",
    "13",
    "61",
    "27",
    "251",
    "13",
    "151",
    "165",
    "156",
    "202",
    "157",
    "55",
    "150",
    "162",
    "51",
    "44",
    "155",
    "14",
    "218",
    "2",
    "147",
    "144",
    "10",
    "23",
    "170",
    "65",
    "145",
    "206",
    "112",
    "190",
    "183",
    "245",
    "142",
    "32",
    "236",
    "214",
    "15",
    "135",
    "120",
    "83",
    "254",
    "90",
    "159",
    "207",
    "0",
    "229",
    "173",
    "75",
    "168",
    "206",
    "112",
    "174",
    "226",
    "251",
    "24",
    "133",
    "187",
    "138",
    "242",
    "60",
    "99",
    "131",
    "168",
    "245",
    "138",
    "108",
    "202",
    "247",
    "121",
    "218",
    "250",
    "164",
    "115",
    "251",
    "107",
    "61",
    "236",
    "14",
    "189",
    "144",
    "12",
    "136",
    "193",
    "171",
    "100",
    "22",
    "212",
    "228",
    "129",
    "21",
    "17",
    "164",
    "126",
    "85",
    "243",
    "168",
    "85",
    "240",
    "251",
    "148",
    "213",
    "10",
    "18",
    "103",
    "76",
    "20",
    "11",
    "255",
    "46",
    "202",
    "36",
    "160",
    "212",
    "61",
    "21",
    "239",
    "191",
    "19",
    "50",
    "29",
    "52",
    "177",
    "172",
    "2",
    "82",
    "215",
    "249",
    "139",
    "232",
    "95",
    "139",
    "249",
    "106",
    "109",
    "236",
    "7",
    "30",
    "211",
    "161",
    "111",
    "210",
    "188",
    "109",
    "42",
    "199",
    "181",
    "242",
    "180",
    "136",
    "125",
    "1",
    "138",
    "217",
    "121",
    "155",
    "74",
    "101",
    "254",
    "158",
    "113",
    "12",
    "12",
    "210",
    "16",
    "74",
    "179",
    "145",
    "239",
    "181",
    "28",
    "190",
    "103",
    "216",
    "141",
    "239",
    "2",
    "81",
    "133",
    "20",
    "205",
    "253",
    "68",
    "163",
    "245",
    "188",
    "1",
    "222",
    "165",
    "58",
    "196",
    "187",
    "56",
    "96",
    "250",
    "179",
    "81",
    "44",
    "104",
    "205",
    "255",
    "126",
    "185",
    "72",
    "14",
    "99",
    "90",
    "249",
    "193",
    "209",
    "118",
    "111",
    "152",
    "171",
    "219",
    "87",
    "150",
    "168",
    "59",
    "90",
    "141",
    "21",
    "46",
    "132",
    "184",
    "142",
    "243",
    "81",
    "48",
    "106",
    "134",
    "143",
    "145",
    "192",
    "252",
    "144",
    "23",
    "207",
    "143",
    "81",
    "6",
    "188",
    "226",
    "164",
    "218",
    "105",
    "11",
    "44",
    "16",
    "76",
    "86",
    "222",
    "82",
    "67",
    "193",
    "85",
    "150",
    "143",
    "136",
    "57",
    "66",
    "247",
    "90",
    "226",
    "159",
    "118",
    "30",
    "74",
    "31",
    "34",
    "214",
    "131",
    "22",
    "214",
    "177",
    "144",
    "114",
    "44",
    "138",
    "131",
    "155",
    "64",
    "102",
    "41",
    "142",
    "81",
    "255",
    "36",
    "47",
    "75",
    "68",
    "151",
    "181",
    "192",
    "233",
    "214",
    "222",
    "67",
    "77",
    "227",
    "99",
    "51",
    "38",
    "82",
    "145",
    "62",
    "194",
    "45",
    "2",
    "137",
    "37",
    "140",
    "164",
    "207",
    "98",
    "209",
    "222",
    "132",
    "63",
    "190",
    "246",
    "229",
    "44",
    "204",
    "195",
    "196",
    "20",
    "172",
    "228",
    "160",
    "88",
    "125",
    "128",
    "125",
    "252",
    "83",
    "126",
    "219",
    "206",
    "239",
    "210",
    "20",
    "45",
    "51",
    "128",
    "161",
    "226",
    "123",
    "88",
    "196",
    "53",
    "231",
    "18",
    "86",
    "229",
    "232",
    "73",
    "252",
    "2",
    "106",
    "76",
    "101",
    "168",
    "9",
    "154",
    "100",
    "113",
    "47",
    "181",
    "84",
    "189",
    "226",
    "180",
    "79",
    "135",
    "207",
    "31",
    "17",
    "50",
    "158",
    "8",
    "112",
    "22",
    "49",
    "157",
    "238",
    "221",
    "17",
    "92",
    "149",
    "154",
    "253",
    "196",
    "76",
    "4",
    "208",
    "253",
    "249",
    "112",
    "216",
    "106",
    "34",
    "247",
    "207",
    "24",
    "115",
    "8",
    "209",
    "111",
    "110",
    "127",
    "111",
    "63",
    "145",
    "169",
    "219",
    "51",
    "76",
    "2",
    "190",
    "247",
    "234",
    "119",
    "69",
    "103",
    "216",
    "165",
    "230",
    "117",
    "10",
    "199",
    "99",
    "141",
    "180",
    "19",
    "57",
    "218",
    "45",
    "41",
    "253",
    "131",
    "143",
    "236",
    "131",
    "255",
    "111",
    "117",
    "213",
    "173",
    "49",
    "173",
    "191",
    "126",
    "101",
    "234",
    "240",
    "40",
    "58",
    "84",
    "231",
    "242",
    "154",
    "98",
    "171",
    "180",
    "109",
    "65",
    "110",
    "240",
    "24",
    "170",
    "114",
    "134",
    "119",
    "94",
    "180",
    "252",
    "221",
    "25",
    "243",
    "226",
    "69",
    "242",
    "119",
    "184",
    "133",
    "93",
    "111",
    "94",
    "229",
    "255",
    "229",
    "232",
    "149",
    "68",
    "112",
    "204",
    "18",
    "219",
    "86",
    "89",
    "152",
    "58",
    "91",
    "68",
    "107",
    "16",
    "225",
    "172",
    "129",
    "79",
    "108",
    "101",
    "140",
    "207",
    "11",
    "160",
    "243",
    "95",
    "9",
    "98",
    "245",
    "50",
    "203",
    "184",
    "150",
    "38",
    "177",
    "112",
    "130",
    "5",
    "188",
    "53",
    "98",
    "227",
    "133",
    "178",
    "229",
    "101",
    "117",
    "140",
    "223",
    "211",
    "72",
    "126",
    "70",
    "235",
    "247",
    "53",
    "57",
    "17",
    "170",
    "132",
    "35",
    "141",
    "48",
    "174",
    "120",
    "121",
    "178",
]
